version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://smartadmin_user:smartadmin_pass@db:5432/smartadmin_db
      - SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=smartadmin_user
      - POSTGRES_PASSWORD=smartadmin_pass
      - POSTGRES_DB=smartadmin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: